import {newRoom,addPlayer,advance,action,publicState} from './engine.js';
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});}
function validate(a){if(!a||typeof a!=='object')throw Error('Invalid request.');if(typeof a.token!=='string'||!/^[a-f0-9-]{36}$/.test(a.token))throw Error('Invalid session.');if(a.type!=='create'&&(typeof a.code!=='string'||!/^[A-Z0-9]{6}$/.test(a.code)))throw Error('Invalid room code.');if(a.command&&JSON.stringify(a.command).length>500)throw Error('Invalid command.');}
export function createGameHandler(storeFactory,clock=Date.now){return async function game(request){
if(request.method!=='POST')return json({error:'Use POST.'},405);
try{if(Number(request.headers.get('content-length')||0)>6000)return json({error:'Request too large.'},413);const text=await request.text();if(text.length>6000)return json({error:'Request too large.'},413);const a=JSON.parse(text);validate(a);if(!['create','join','sync','leave'].includes(a.type))return json({error:'Unknown request type.'},400);let now=clock();const store=storeFactory();
if(a.type==='create'){let code;for(let tries=0;tries<6;tries++){code=Array.from(crypto.getRandomValues(new Uint8Array(6)),v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join('');let s=newRoom(code,now);let p=addPlayer(s,String(a.name||'Wizard'),a.token,now);const saved=await store.set('rooms/'+code,JSON.stringify(s),{onlyIfNew:true,metadata:{expires:String(now+21600000)}});if(saved.modified)return json({state:publicState(s),playerId:p.id});}return json({error:'Could not create a room. Try again.'},503);}
const key='rooms/'+a.code;for(let attempt=0;attempt<8;attempt++){const obj=await store.getWithMetadata(key,{type:'json',consistency:'strong'});if(!obj)return json({error:'Room not found. Check the code.'},404);if(!obj.etag)return json({error:'Room storage did not return a revision. Please retry.'},503);let s=obj.data;now=Math.max(clock(),s.last);if(now-s.last>21600000)return json({error:'This room has expired. Create a new one.'},410);let p=s.players.find(p=>p.token===a.token);if(a.type==='join'){if(!p)p=addPlayer(s,String(a.name||'Wizard'),a.token,now);else p.seen=now;}
else{if(!p)return json({error:'Your session expired. Rejoin the room.'},401);if(a.type==='leave'){p.seen=now-31000;if(s.phase==='lobby'||s.phase==='finished')s.players=s.players.filter(q=>q.id!==p.id);}else if(a.type==='sync'){p.seen=now;}}
// Run simulation using previously acknowledged inputs before applying new actions.
advance(s,now);let error=null;if(a.type==='sync')try{action(s,p,a,now);}catch(e){error=e.message;}
const saved=await store.set(key,JSON.stringify(s),{onlyIfMatch:obj.etag,metadata:{expires:String(now+21600000)}});if(saved.modified)return error?json({error},400):json({state:publicState(s),playerId:p?.id});}
return json({error:'Room is busy. Please retry.'},409);
}catch(e){return json({error:e.message||'Room service error.'},400);}};}
