const $=id=>document.getElementById(id);const show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
let state=null,myId=null,room=null,token=null,isPractice=false,joinMode='create',seq=Date.now(),busy=false,queue=[],keys={},input={mx:0,my:0,ax:600,ay:500,fire:false},selected=0,filter=0,lastRound=-1,pollTimer=null,lastRender=0,snapshotAt=0,transform={scale:1,ox:0,oy:0},lastNet=0,practiceTimer=null,pins=JSON.parse(localStorage.getItem('ec-pins')||'["fireball","heal","shield"]');
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function setHTML(id,html){const el=$(id);if(el.innerHTML!==html)el.innerHTML=html;}
function focusArena(){$('battle').focus({preventScroll:true});}
function startBattle(){if(!state)return;const connected=state.players.filter(p=>!p.teamBot&&Date.now()-p.seen<30000);if(connected.length<2){toast('Add a second player before starting. Use another tab, browser, or device.');return;}if(myId!==state.host){toast('Only the host can start the battle.');return;}sendCommand({type:'start'});}
function me(){return state?.players.find(p=>p.id===myId);}
function toast(s){$('toast').textContent=s;show('toast');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>hide('toast'),2800);}
function showHelp(){show('helpmodal');syncBasicAttack();}
function openJoin(mode){joinMode=mode;$('jointitle').textContent=mode==='create'?'Create your room.':'Join your friends.';$('codefield').classList.toggle('hidden',mode==='create');$('nickname').value=localStorage.getItem('ec-name')||'';$('joinerror').textContent='';show('joinmodal');$('nickname').focus();}
async function api(data){const r=await fetch('/.netlify/functions/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let result;try{result=await r.json();}catch{throw Error('The game server is unavailable. Try again shortly.');}if(!r.ok)throw Error(result.error||'Request failed.');return result;}
async function connect(){const name=$('nickname').value.trim();if(!name)return;const code=$('joincode').value.trim().toUpperCase();if(joinMode==='join'&&!/^[A-Z0-9]{6}$/.test(code)){$('joinerror').textContent='Enter the six-character room code.';return;}$('joinbtn').disabled=true;try{token=uid();let r=await api({type:joinMode,name,code,token});isPractice=false;room=r.state.code;myId=r.playerId;state=r.state;snapshotAt=performance.now();localStorage.setItem('ec-name',name);sessionStorage.setItem('ec-session',JSON.stringify({room,token,myId}));hide('joinmodal');hide('home');show('lobby');startPolling();renderUI();}catch(e){$('joinerror').textContent=e.message;}finally{$('joinbtn').disabled=false;}}
function sendCommand(c){if(!state)return;queue.push({command:c,seq:++seq});if(isPractice){drainPractice();renderUI();}else poll();}
function settings(){sendCommand({type:'settings',mode:$('mode').value,pace:Number($('pace').value),supplies:$('supplies').checked,botDifficulty:$('botdifficulty').value});}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(poll,120);}
async function poll(){if(busy||!room||isPractice)return;busy=true;const activeRoom=room,activeToken=token;const a=queue[0];try{let r=await api({type:'sync',code:room,token,input,...a});if(room!==activeRoom||token!==activeToken||isPractice)return;state=r.state;snapshotAt=performance.now();lastNet=snapshotAt;if(a){queue.shift();confirmPrepared(a.command);}renderUI();}catch(e){if(a&&e.message!=='Room is busy. Please retry.'){queue.shift();toast(e.message);}if(e.message.includes('expired')||e.message.includes('not found'))leave();else if(performance.now()-lastNet>4000)$('statushint').textContent='Connection interrupted — retrying…';}finally{busy=false;}}
function leave(){clearInterval(pollTimer);clearInterval(practiceTimer);if(room&&!isPractice)api({type:'leave',code:room,token}).catch(()=>{});room=null;state=null;lockedTarget=null;currentTarget=null;queue=[];keys={};moveTouch=null;aimTouch=null;input.mx=0;input.my=0;input.fire=false;mouseFire=false;resetTouchControls();myId=null;sessionStorage.removeItem('ec-session');hide('game');hide('lobby');hide('resultmodal');hide('recipesmodal');show('header');show('home');isPractice=false;}
async function copyCode(){
 try{if(!navigator.clipboard?.writeText)throw Error('Fallback');await navigator.clipboard.writeText(room);toast('Room code copied: '+room);return;}catch{}
 const el=document.createElement('textarea');el.value=room;el.readOnly=true;el.style.cssText='position:fixed;top:0;left:0;opacity:.01;font-size:16px';document.body.appendChild(el);el.focus();el.select();el.setSelectionRange(0,el.value.length);
 let copied=false;try{copied=document.execCommand('copy');}catch{}el.remove();
 if(copied)toast('Room code copied: '+room);else{show('copymodal');$('manualcode').value=room;$('manualcode').focus();$('manualcode').select();toast('Touch and hold the code to copy it.');}
}
function backLobby(){hide('resultmodal');hide('game');show('header');show('lobby');}
let tray=[0,0,0,0];
function openRecipes(){show('recipesmodal');syncBasicAttack();renderRecipes();renderTray();}
function renderTray(){let total=tray.reduce((a,b)=>a+b,0);$('traycontrols').innerHTML=ELEMENTS.map((e,i)=>'<button class="small" style="color:var(--'+e+')" onclick="if(tray.reduce((a,b)=>a+b,0)<5){tray['+i+']++;renderTray()}">'+e+' + ('+tray[i]+')</button>').join('');let r=RECIPES.find(r=>r.cost.every((v,i)=>v===tray[i]));$('trayresult').innerHTML=r?'<strong style="color:var(--ink)">'+r.name+'</strong> · '+r.description+' <button class="small" '+(affordable(r)?'':'disabled')+' onclick="sendCommand({type:\'load\',recipe:\''+r.id+'\'})">Craft</button>':total<2?'Choose two to five ingredients. Order does not matter.':'No recipe for this combination. Nothing is consumed.';}
function suggestedRecipes(p){
 if(!p||!p.alive)return [];
 const pay=r=>r.cost.every((n,i)=>p.inv[i]>=n),def=r=>['heal','shield'].includes(r.kind);
 const rank=r=>r.tier*10+(r.heal?(p.hp<75?80:-50):0)+(r.shield?(p.shield<10?25:-30):0);
 const available=RECIPES.filter(pay).sort((a,b)=>rank(b)-rank(a));
 const defense=available.find(def)||RECIPES.find(r=>r.id===(p.hp<75?'heal':'shield'));
 const picks=available.filter(r=>r.id!==defense.id).slice(0,5);
 for(const r of RECIPES)if(picks.length<5&&r.id!==defense.id&&!picks.some(x=>x.id===r.id))picks.push(r);
 return [...picks,defense];
}
let lockedTarget=null,currentTarget=null,lastDirection={x:1,y:0};
function resolveTarget(s,p,lock,current,range){
 const candidates=s.players.filter(q=>enemies(s,p,q)&&dist(p,q)<=range&&clearRoute(s,p,q)).sort((a,b)=>dist(p,a)-dist(p,b));
 const preferred=candidates.find(q=>q.id===lock);if(preferred)return preferred;
 const previous=candidates.find(q=>q.id===current),nearest=candidates[0];
 return previous&&nearest&&dist(p,previous)<=dist(p,nearest)*1.25+35?previous:nearest||null;
}
function updateTarget(range=480){const p=me();if(!p||!state)return null;const t=resolveTarget(state,p,lockedTarget,currentTarget,range);currentTarget=t?.id||null;if(t){input.ax=t.x;input.ay=t.y;}else{input.ax=clamp(p.x+lastDirection.x*range,0,1200);input.ay=clamp(p.y+lastDirection.y*range,0,1000);}return t;}
function selectOpponent(e){const p=me();if(!p||!p.alive)return;const point={x:(e.clientX-transform.ox)/transform.scale,y:(e.clientY-transform.oy)/transform.scale};const target=state.players.filter(q=>enemies(state,p,q)&&dist(q,point)<Math.max(24,24/transform.scale)).sort((a,b)=>dist(a,point)-dist(b,point))[0];lockedTarget=target?.id||null;updateTarget();toast(target?'Target locked: '+target.name:'Automatic targeting');}
function craftSuggested(id){
 const r=RECIPES.find(r=>r.id===id),p=me();if(!affordable(r)){toast('Collect the ingredients or wait for the cooldown.');return;}
 let aimPoint={ax:p.x,ay:p.y};
 if(r.kind==='dash'){aimPoint={ax:clamp(p.x+lastDirection.x*r.range,0,1200),ay:clamp(p.y+lastDirection.y*r.range,0,1000)};}
 else if(!['heal','shield'].includes(r.kind)&&!r.heal){const t=updateTarget(r.range||480);if(!t){toast('No visible opponent in spell range.');return;}aimPoint={ax:t.x,ay:t.y};}
 sendCommand({type:'load',recipe:id,fromSuggestion:true,instant:true,aim:aimPoint});
}
function confirmPrepared(c){if(!c?.fromSuggestion)return;const r=RECIPES.find(r=>r.id===c.recipe);selected=0;if(!matchMedia('(pointer:coarse)').matches)focusArena();toast(['heal','shield'].includes(r.kind)?r.name+' used.':c.instant?r.name+' cast.':r.name+' loaded — aim and release to cast.');}
function needsOpponent(r){return !!r&&!['heal','shield','dash'].includes(r.kind)&&!r.heal;}
function spellInRange(r,p=me()){return !needsOpponent(r)||!!(p&&state&&resolveTarget(state,p,lockedTarget,currentTarget,r.range||480));}
function refreshSpellAvailability(){
 const p=me();if(!p)return;
 for(let i=0;i<6;i++){const b=$('suggestion'+i),r=RECIPES.find(r=>r.id===b.recipeId);if(!r)continue;
 const inRange=spellInRange(r,p),ready=affordable(r)&&inRange;b.disabled=!ready;b.classList.toggle('castready',ready);
 const missing=r.cost.map((n,j)=>n>p.inv[j]?(n-p.inv[j])+' '+ELEMENTS[j]:null).filter(Boolean);
 $('suggestdest'+i).textContent=missing.length?'Need '+missing.join(', '):!inRange?'Out of range':p.items[0]&&!['heal','shield'].includes(r.kind)?'Cast loaded spell first':!affordable(r)?'Cooling down':['heal','shield'].includes(r.kind)?'Use now':'Cast now';
 }
}
function renderSuggestions(p){
 const picks=suggestedRecipes(p);$('quicklabel').textContent=(lockedTarget?'TARGET LOCKED':'AUTO TARGET')+' · TAP / 1–6 TO CAST · 6 DEFENSE';
 for(let i=0;i<6;i++){const r=picks[i],b=$('suggestion'+i);b.classList.toggle('hidden',!r);b.recipeId=r?.id;b.disabled=!r||!affordable(r);
 if(r){$('suggestname'+i).textContent=(i+1)+'. '+r.name;setHTML('suggestcost'+i,costHTML(r));b.title=r.description;}}
 refreshSpellAvailability();
}

function activateSuggestion(button){if(performance.now()<(button.ignoreClickUntil||0))return;craftSuggested(button.pressedRecipe||button.recipeId);button.pressedRecipe=null;}
for(let i=0;i<6;i++)$('suggestion'+i).addEventListener('pointerdown',e=>{
 const button=e.currentTarget;if(button.disabled)return;
 button.pressedRecipe=button.recipeId;
 if(e.pointerType==='touch'){e.preventDefault();e.stopPropagation();button.ignoreClickUntil=performance.now()+800;craftSuggested(button.recipeId);button.pressedRecipe=null;}
});
function affordable(r){const p=me();return !!r&&!!p&&p.alive&&state.phase==='playing'&&r.cost.every((n,i)=>p.inv[i]>=n)&&(['heal','shield'].includes(r.kind)?(r.kind!=='heal'||state.t>=p.potionAt)&&(r.tier<4||state.t>=p.specialAt):!p.items[0]&&state.t>=p.attackAt&&(r.tier<4||state.t>=p.specialAt));}
function costHTML(r){return r.cost.map((n,i)=>n?'<span style="color:var(--'+ELEMENTS[i]+')">'+['◆','●','■','✦'][i]+' '+n+'</span>':'').join('');}
function renderRecipes(){const choices=[[0,'All recipes'],[2,'2 elements'],[3,'3 elements'],[4,'4 elements'],[5,'5 elements']];$('filters').innerHTML=choices.map(([n,label])=>'<button class="small '+(filter===n?'active':'')+'" onclick="filter='+n+';renderRecipes()">'+label+'</button>').join('');$('recipegrid').innerHTML=RECIPES.filter(r=>!filter||r.tier===filter).map(r=>'<article class="recipe"><div class="row"><h3>'+r.name+'</h3><button class="small" aria-label="Pin '+r.name+'" onclick="pin(\''+r.id+'\')">'+(pins.includes(r.id)?'★':'☆')+'</button></div><div class="cost">'+costHTML(r)+'</div><p>'+r.description+(r.tier===3?' · '+(r.damage?r.damage+' damage':r.heal?r.heal+' healing':r.shield?r.shield+' shield':'increased reach'):'')+'</p><button class="small" '+(affordable(r)?'':'disabled')+' onclick="sendCommand({type:\'load\',recipe:\''+r.id+'\'})">Craft'+(r.tier>=4?' · power spell':'')+'</button></article>').join('');}
function pin(id){if(pins.includes(id))pins=pins.filter(x=>x!==id);else{if(pins.length>=3){toast('Unpin a favorite first (maximum three).');return;}pins.push(id);}localStorage.setItem('ec-pins',JSON.stringify(pins));renderRecipes();renderHUD();}
function renderUI(){if(!state)return;const p=me();if(!p)return;const playing=state.phase==='playing';if(playing){hide('home');hide('lobby');hide('header');hide('resultmodal');show('game');if(lastRound!==state.round){lastRound=state.round;queue=[];selected=0;hide('recipesmodal');focusArena();}}
if(state.phase==='finished'&&lastRound!==-state.round){lastRound=-state.round;show('resultmodal');$('winner').textContent=state.winner==='Draw'?'A magical draw.':state.winner+' wins!';$('results').innerHTML=state.results.map((p,i)=>'<tr><td><span style="color:'+p.color+'">'+(i+1)+'. '+escapeHTML(p.name)+'</span></td><td>'+p.kills+'</td><td>'+p.damage+'</td></tr>').join('');$('resultnote').textContent=state.settings.mode==='skirmish'?'Ranked by eliminations, then damage dealt.':'Placement follows survival. Eliminations and damage are bonus statistics.';}
$('roomcode').textContent=room||'PRACTICE';setHTML('players',state.players.map(q=>'<div class="playerrow"><div class="avatar" style="--pc:'+q.color+'">'+escapeHTML(q.name[0].toUpperCase())+'</div><div><strong>'+escapeHTML(q.name)+'</strong><br><small>'+(q.teamBot?'Computer · '+q.difficulty:q.id===state.host?'Host':q.id===myId?'You':'Wizard')+(state.settings.mode==='teams'?' · Team '+(state.players.indexOf(q)%2===0?'Sun':'Moon'):'')+'</small></div><span class="status" style="color:'+(q.ready?'var(--air)':'var(--muted)')+'">'+(q.teamBot?'AI teammate':q.spectator?'Spectating':Date.now()-q.seen>3000?'Reconnecting…':q.ready?'Ready ✓':'In room')+'</span></div>').join(''));const host=myId===state.host;$('start').disabled=!host;$('rematch').disabled=!host&&!isPractice;$('ready').textContent=p.ready?'Ready ✓':'Ready up';$('lobbynote').textContent=host?'Start when at least two players are here. Each tab can join separately. Ready indicators are optional.':'Your host starts the battle. Each tab can join as a separate wizard.';for(const id of ['mode','pace','supplies','botdifficulty'])$(id).disabled=!host;$('botdifficulty').value=state.settings.botDifficulty||'medium';$('botsettings').classList.toggle('hidden',state.settings.mode!=='teams');$('mode').value=state.settings.mode;$('pace').value=state.settings.pace;$('supplies').checked=state.settings.supplies;renderHUD();if(!$('recipesmodal').classList.contains('hidden')){const pkey=p.inv.join(',')+':'+p.items.join(',');if(window.recipeKey!==pkey){window.recipeKey=pkey;renderRecipes();renderTray();}}}
function renderHUD(){let p=me();if(!p)return;$('myname').textContent=p.name;$('hp').textContent=Math.ceil(p.hp)+' / 100';$('healthfill').style.width=p.hp+'%';$('shieldtext').textContent=p.shield>0?'Shield '+Math.ceil(p.shield)+' · '+Math.max(0,Math.ceil(p.shieldUntil-state.t))+'s':p.alive?'No shield':'Spectating';let alive=state.players.filter(p=>p.alive&&!p.spectator).length;$('alivecount').textContent=isPractice?'Practice arena':state.settings.mode==='skirmish'?'Skirmish · '+p.kills+' eliminations':alive+' wizard'+(alive===1?'':'s')+' remain';$('clock').textContent=Math.floor(state.t/60).toString().padStart(2,'0')+':'+Math.floor(state.t%60).toString().padStart(2,'0');const stormTime=90/state.settings.pace;$('storm').textContent=state.settings.mode==='skirmish'?Math.max(0,Math.ceil(180-state.t))+'s left':state.t<stormTime?'Storm in '+Math.ceil(stormTime-state.t)+'s':'Storm closing';setHTML('inventory',ELEMENTS.map((e,i)=>'<span style="color:var(--'+e+')">'+['◆','●','■','✦'][i]+'<span class="count">'+p.inv[i]+'</span></span>').join('')+'<span style="font-size:10px;color:var(--muted)">'+p.inv.reduce((a,b)=>a+b,0)+'/8</span>');
const loaded=RECIPES.find(r=>r.id===p.items[0]);$('loadedname').textContent=loaded?loaded.name:'No spell loaded';$('loadedhint').textContent=loaded?'Aim and release / click or F to cast':'Choose a suggestion below';
renderSuggestions(p);let potion=Math.ceil(p.potionAt-state.t),power=Math.ceil(p.specialAt-state.t);$('statushint').textContent=!p.alive?(state.settings.mode==='skirmish'?'Respawning in '+Math.max(0,Math.ceil(p.respawnAt-state.t))+'s':'Eliminated · watching the remaining wizards'):isPractice?'Practice: ingredient pack refills when empty · three sparring bots':(potion>0?'Potion '+potion+'s ':'')+(power>0?'Power spell '+power+'s':'');setHTML('feed',state.events.filter(e=>state.t-e.t<7).slice(0,3).map(e=>'<div>'+escapeHTML(e.text)+'</div>').join(''));}
function selectSlot(i){selected=i;const r=RECIPES.find(r=>r.id===me()?.items[i]);if(!r){openRecipes();return;}if(!matchMedia('(pointer:coarse)').matches||['heal','shield'].includes(r.kind))sendCommand({type:'cast',slot:i});renderHUD();}
let mouseFire=false,touchFire=false;
function syncBasicAttack(){input.fire=!!(state?.phase==='playing'&&me()?.alive&&$('recipesmodal').classList.contains('hidden')&&$('helpmodal').classList.contains('hidden')&&updateTarget(480)&&(mouseFire||touchFire||keys[' ']));}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys[k]=true;syncBasicAttack();if(!e.repeat&&state?.phase==='playing'&&$('recipesmodal').classList.contains('hidden')&&$('helpmodal').classList.contains('hidden')){if(!matchMedia('(pointer:coarse)').matches&&/^[1-6]$/.test(k)){e.preventDefault();const button=$('suggestion'+(Number(k)-1));if(!button.disabled)craftSuggested(button.recipeId);}else if(k==='f')sendCommand({type:'cast',slot:0});}if(k==='e'&&!e.repeat){if($('recipesmodal').classList.contains('hidden'))openRecipes();else hide('recipesmodal');}if(k==='escape'){hide('recipesmodal');hide('helpmodal');}});
window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.key===' '&&state?.phase==='playing')e.preventDefault();syncBasicAttack();});window.addEventListener('blur',()=>{keys={};mouseFire=false;resetTouchControls();input.mx=0;input.my=0;input.fire=false;});
$('battle').addEventListener('pointerdown',e=>{if(state?.phase!=='playing')return;e.preventDefault();selectOpponent(e);});
const touchResetters=[];let moveTouch=null,aimTouch=null;function resetTouchControls(){moveTouch=null;aimTouch=null;touchFire=false;for(const reset of touchResetters)reset();}function stick(id,kind){const el=$(id),knob=el.querySelector('.knob');let active=null;function set(e){const b=el.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,len=Math.hypot(dx,dy),radius=b.width/2-12,m=Math.min(len,radius);let nx=len?dx/len:0,ny=len?dy/len:0;knob.style.transform='translate('+nx*m+'px,'+ny*m+'px)';if(kind==='move'){moveTouch={x:nx*m/radius,y:ny*m/radius};}else{const p=me();if(!p)return;const r=RECIPES.find(r=>r.id===p.items[selected]);let reach=(r?.range||480)*Math.max(.08,m/radius);aimTouch={x:nx,y:ny,strength:m/radius};input.ax=clamp(p.x+nx*reach,0,1200);input.ay=clamp(p.y+ny*reach,0,1000);}}
el.addEventListener('pointerdown',e=>{e.preventDefault();if(active!==null)return;active=e.pointerId;el.setPointerCapture(active);set(e);});el.addEventListener('pointermove',e=>{if(active===e.pointerId)set(e);});function end(e){if(active!==e.pointerId)return;active=null;knob.style.transform='';if(kind==='move'){moveTouch=null;input.mx=0;input.my=0;}else{aimTouch=null;if(e.type==='pointerup')sendCommand({type:'cast',slot:selected});}}el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end);touchResetters.push(()=>{active=null;knob.style.transform='';});}
stick('moveStick','move');stick('aimStick','aim');
const basicTouches=new Set();
$('basicbtn').addEventListener('pointerdown',e=>{e.preventDefault();basicTouches.add(e.pointerId);e.currentTarget.setPointerCapture(e.pointerId);touchFire=basicTouches.size>0;syncBasicAttack();});
function releaseBasic(e){basicTouches.delete(e.pointerId);touchFire=basicTouches.size>0;syncBasicAttack();}
for(const type of ['pointerup','pointercancel','lostpointercapture'])$('basicbtn').addEventListener(type,releaseBasic);
touchResetters.push(()=>basicTouches.clear());

function practice(){leave();isPractice=true;room='PRACTICE';token=uid();state=newRoom(room,Date.now());let p=addPlayer(state,localStorage.getItem('ec-name')||'Apprentice',token,Date.now());myId=p.id;for(let i=0;i<3;i++){let b=addPlayer(state,['Ember Bot','Frost Bot','Gale Bot'][i],uid(),Date.now());b.bot=true;}start(state,Date.now());p.inv=[2,2,2,2];state.settings.mode='skirmish';lastRound=-1;hide('home');practiceTimer=setInterval(()=>{if(!state||!isPractice)return;const now=Date.now();const p=me();p.seen=now;p.input={...input};if(p.inv.reduce((a,b)=>a+b,0)===0)p.inv=[2,2,2,2];for(const b of state.players.filter(p=>p.bot)){b.seen=now;const angle=state.t*.35+state.players.indexOf(b)*2;b.input={mx:Math.cos(angle),my:Math.sin(angle),ax:p.x,ay:p.y,fire:dist(b,p)<400&&Math.sin(state.t+b.team)>0};}drainPractice();advance(state,now);snapshotAt=performance.now();renderUI();},33);renderUI();}
function drainPractice(){while(queue.length){let a=queue.shift();try{action(state,me(),{...a,input},Date.now());confirmPrepared(a.command);if(a.command.type==='start'){me().inv=[2,2,2,2];state.settings.mode='skirmish';}}catch(e){toast(e.message);}}}
function fitCanvas(canvas){const dpr=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}return {w,h,dpr};}
function circle(ctx,x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
const EC=['#ff9669','#83d5ff','#d8c185','#9ce1c5'];
function drawIngredient(c,x,y,i,t){c.save();c.translate(x,y+Math.sin(t*2+x)*2);c.shadowColor=EC[i];c.shadowBlur=14;c.fillStyle=EC[i];c.beginPath();if(i===0){c.moveTo(0,-10);c.lineTo(8,1);c.lineTo(0,9);c.lineTo(-8,1);}else if(i===1){c.arc(0,1,7,0,Math.PI*2);}else if(i===2){c.rect(-7,-7,14,14);}else{c.moveTo(0,-10);c.lineTo(3,-3);c.lineTo(10,0);c.lineTo(3,3);c.lineTo(0,10);c.lineTo(-3,3);c.lineTo(-10,0);c.lineTo(-3,-3);}c.fill();c.restore();}
function drawArena(canvas,s,decor=false){const {w,h,dpr}=fitCanvas(canvas),c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#15151f';c.fillRect(0,0,w,h);let scale=Math.min(w/1200,h/1000),ox=(w-1200*scale)/2,oy=(h-1000*scale)/2;if(decor){scale=Math.max(w/1200,h/1000)*1.08;ox=(w-1200*scale)/2;oy=(h-1000*scale)/2;}else transform={scale,ox,oy};c.translate(ox,oy);c.scale(scale,scale);c.fillStyle='#20202c';c.fillRect(0,0,1200,1000);c.strokeStyle='#ffffff06';c.lineWidth=1;for(let x=0;x<=1200;x+=50){c.beginPath();c.moveTo(x,0);c.lineTo(x,1000);c.stroke();}for(let y=0;y<=1000;y+=50){c.beginPath();c.moveTo(0,y);c.lineTo(1200,y);c.stroke();}
c.strokeStyle='#4f426755';c.lineWidth=2;circle(c,600,500,165,null,'#4f426755');circle(c,600,500,180,null,'#4f426733');for(let i=0;i<8;i++){let a=i*Math.PI/4;c.beginPath();c.moveTo(600+Math.cos(a)*165,500+Math.sin(a)*165);c.lineTo(600+Math.cos(a)*190,500+Math.sin(a)*190);c.stroke();}
for(const o of s.obstacles||OBSTACLES){c.fillStyle='#11111b';c.fillRect(o.x+5,o.y+8,o.w,o.h);c.fillStyle='#393645';c.fillRect(o.x,o.y,o.w,o.h);c.fillStyle='#4a4459';c.fillRect(o.x,o.y,o.w,5);c.strokeStyle='#5c5066';c.strokeRect(o.x,o.y,o.w,o.h);}
for(const z of s.zones){const warning=s.t<z.start;c.globalAlpha=warning?.2:.3;circle(c,z.x,z.y,z.radius,z.color);c.globalAlpha=1;c.lineWidth=2;c.setLineDash(warning?[8,8]:[]);circle(c,z.x,z.y,z.radius,null,z.color);c.setLineDash([]);if(warning){c.fillStyle=z.color;c.font='bold 14px system-ui';c.textAlign='center';c.fillText('!',z.x,z.y+5);}}
for(const q of s.sources){if(s.t>=q.respawn)drawIngredient(c,q.x,q.y,q.element,s.t);else{c.globalAlpha=.25;circle(c,q.x,q.y,7,null,EC[q.element]);c.globalAlpha=1;}}for(const q of s.pickups)drawIngredient(c,q.x,q.y,q.element,s.t);
for(const b of s.shots){c.save();c.shadowBlur=12;c.shadowColor=b.color;circle(c,b.x,b.y,b.damage>10?7:4,b.color);c.restore();}
for(const p of s.players){if(!p.alive)continue;if(p.id===currentTarget){c.lineWidth=3;circle(c,p.x,p.y,29,null,lockedTarget===p.id?'#ffe09b':'#b5a0ff');}circle(c,p.x,p.y+8,16,'#0005');if(p.shield>0){c.lineWidth=3;circle(c,p.x,p.y,23,null,'#83d5ff');}if(p.spawnProtection>s.t){c.lineWidth=1;circle(c,p.x,p.y,27,null,'#ffffff66');}c.save();c.shadowColor=p.color;c.shadowBlur=12;circle(c,p.x,p.y,14,p.color);c.restore();c.fillStyle='#221d33';c.beginPath();c.moveTo(p.x-8,p.y-6);c.lineTo(p.x,p.y-21);c.lineTo(p.x+8,p.y-6);c.fill();circle(c,p.x-4,p.y-1,2,'#221d33');circle(c,p.x+4,p.y-1,2,'#221d33');c.fillStyle='#f5efff';c.textAlign='center';c.font='12px system-ui';c.fillText(p.name+(p.id===myId?' • YOU':''),p.x,p.y-34);c.fillStyle='#11111d';c.fillRect(p.x-19,p.y+23,38,4);c.fillStyle=p.color;c.fillRect(p.x-19,p.y+23,38*p.hp/100,4);if(s.settings.mode==='teams'){c.fillStyle=p.team===0?'#ffe09b':'#a7c8ff';c.font='9px system-ui';c.fillText(p.team===0?'SUN':'MOON',p.x,p.y+40);}}
const p=s.players.find(p=>p.id===myId);if(!decor&&p?.alive){let r=RECIPES.find(r=>r.id===p.items[selected])||{kind:'bolt',range:480};const a=aim(p,input,r.range||500);c.save();c.strokeStyle='#e2d6ff88';c.fillStyle='#b5a0ff10';c.lineWidth=1.5;c.setLineDash([5,6]);if(['zone','meteor','mine'].includes(r.kind)){circle(c,a.x,a.y,r.radius||52,'#b5a0ff15','#e2d6ff88');c.beginPath();c.moveTo(p.x,p.y);c.lineTo(a.x,a.y);c.stroke();}else if(r.kind==='cone'){let angle=Math.atan2(a.dy,a.dx);c.beginPath();c.moveTo(p.x,p.y);c.arc(p.x,p.y,r.range,angle-.98,angle+.98);c.closePath();c.fill();c.stroke();}else if(['heal','shield','wave'].includes(r.kind)){circle(c,p.x,p.y,r.range||27,'#b5a0ff10','#e2d6ff88');}else{c.beginPath();c.moveTo(p.x+a.dx*23,p.y+a.dy*23);c.lineTo(p.x+a.dx*r.range,p.y+a.dy*r.range);c.stroke();circle(c,a.x,a.y,7,null,'#e2d6ff88');}c.restore();}
if(s.radius<760){c.fillStyle='#ab5de428';c.beginPath();c.rect(0,0,1200,1000);c.arc(600,500,s.radius,0,Math.PI*2,true);c.fill('evenodd');c.lineWidth=4;circle(c,600,500,s.radius,null,'#c48afa');}c.strokeStyle='#51445f';c.lineWidth=3;c.strokeRect(0,0,1200,1000);}
let artState=newRoom('ART',Date.now());artState.t=0;artState.radius=760;for(let i=0;i<4;i++){let p=addPlayer(artState,['Ember','Gale','Terra','Frost'][i],uid(),Date.now());p.x=[450,790,700,350][i];p.y=[430,580,290,650][i];}for(let i=0;i<18;i++)artState.sources.push({x:270+(i%6)*130,y:280+Math.floor(i/6)*190,element:i%4,respawn:0});
let visualPlayers=new Map(),previousFrame=0;
function animatedProjectiles(s,elapsed){
 // Draw between server snapshots; combat and collision results remain authoritative.
 const age=clamp(elapsed,0,.18);
 return s.shots.flatMap(b=>{
  if(b.life!==undefined&&b.life<=age)return [];
  const dx=(b.vx||0)*age,dy=(b.vy||0)*age,steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/4));
  let x=b.x,y=b.y;
  for(let i=1;i<=steps;i++){
   const nx=b.x+dx*i/steps,ny=b.y+dy*i/steps;
   if(blocked(nx,ny,3,s.obstacles||OBSTACLES))return [];
   x=nx;y=ny;
  }
  return [{...b,x,y}];
 });
}
function frame(now){const delta=Math.min(.05,(now-previousFrame)/1000||.016);previousFrame=now;syncBasicAttack();if(!moveTouch){input.mx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);input.my=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);}else{input.mx=moveTouch.x;input.my=moveTouch.y;}if(Math.hypot(input.mx,input.my)>0){const n=Math.hypot(input.mx,input.my);lastDirection={x:input.mx/n,y:input.my/n};}updateTarget();if(state?.phase==='playing')refreshSpellAvailability();if(state&&!$('game').classList.contains('hidden')){const players=state.players.map(p=>{let v=visualPlayers.get(p.id)||{x:p.x,y:p.y};if(!p.alive||Math.hypot(p.x-v.x,p.y-v.y)>150){v.x=p.x;v.y=p.y;}else{let f=1-Math.exp(-18*delta);v.x+=(p.x-v.x)*f;v.y+=(p.y-v.y)*f;}visualPlayers.set(p.id,v);return {...p,x:v.x,y:v.y};});const shots=animatedProjectiles(state,(now-snapshotAt)/1000);drawArena($('battle'),{...state,players,shots});}else if(!$('home').classList.contains('hidden')){artState.t=now/1000;artState.shots=[{x:480+(now/5)%240,y:440+(now/10)%100,color:'#ff9669',damage:25}];drawArena($('art'),artState,true);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
(async()=>{let session;try{session=JSON.parse(sessionStorage.getItem('ec-session'));}catch{}if(!session)return;try{let r=await api({type:'sync',code:session.room,token:session.token,input:{mx:0,my:0,fire:false,ax:600,ay:500}});state=r.state;snapshotAt=performance.now();room=session.room;token=session.token;myId=session.myId;seq=Date.now();hide('home');show('lobby');startPolling();renderUI();toast('Reconnected to room '+room);}catch{sessionStorage.removeItem('ec-session');}})();
